[project]
name = "advanced-scripting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Virginia Potestivo", email = "vsilva@madisoncollege.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.93",
]

[project.scripts]
advanced-scripting = "advanced_scripting:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
